name: Build & Create Release
on: workflow_dispatch
jobs:
  build-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Module
        run: python3 test_files/hello_world.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: test_files/hello_world.py
  release:
    runs-on: ubuntu-latest
    needs: build-src
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: src
      - name: Print arifact
        run: ls -la
      - name: create zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          path: hello_world.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
