name: Build & Push Container
on: workflow_dispatch
jobs:
  build-src:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: ${{ secrets.USERNAME }}/test-action:latest, ${{ secrets.USERNAME }}/test-action:${{ github.run_number }}
