name: Shell Commands

on: ["workflow_dispatch"]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: describe the action run
        run: echo "Running a simple workflow executing a single shell command"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
        
  job-chain:
    needs: [run-shell-command]
    runs-on: ubuntu-latest
    steps:
      - name: hello-world
        run: |
          print("hello world")
        shell: python
